//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduatesProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonsProffesions = new HashSet<PersonsProffesion>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Biography { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> GraduateYear { get; set; }
        public Nullable<double> GPAofCertificate { get; set; }
        public string DiplomaPaperTopic { get; set; }
        public string SupervisorOfDiplomaPaper { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public string PhoneNumber { get; set; }
        public string ActivityInStudent { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public bool HasWorkNow { get; set; }
        public bool IsMarried { get; set; }
        public string ReviewsAboutInstitute { get; set; }
        public bool FundedByNBU { get; set; }
        public string GroupName { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual ICollection<PersonsProffesion> PersonsProffesions { get; set; }
    }
}
