//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduatesProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Guid { get; set; }
        public string VirtualUrl { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsOnServer { get; set; }
    
        public virtual ICollection<Person> Persons { get; set; }
    }
}
