//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduatesProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.PersonsProffesions = new HashSet<PersonsProffesion>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> RateInPercent { get; set; }
        public string PositionName { get; set; }
    
        public virtual ICollection<PersonsProffesion> PersonsProffesions { get; set; }
    }
}
